# Generated by Django 4.1.3 on 2022-11-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_books_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.CharField(max_length=1000)),
                ('info', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
