# Generated by Django 4.1.3 on 2022-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about_delete_mainphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
