# Generated by Django 4.1.3 on 2022-11-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
    ]
