# Generated by Django 4.1.3 on 2022-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contact_hobby_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('link', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
