# Generated by Django 4.1.3 on 2022-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='greet',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='info',
        ),
        migrations.AddField(
            model_name='about',
            name='coverImg',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='profileImg',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.TextField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Empty', max_length=1000),
        ),
    ]
